# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aditya Joshi
tagline:          'Wanderer'
description:      'A common platform to compile information about my personalprojects, research and professional experience.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Aditya Joshi'
  url:            https://twitter.com/1adityajoshi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adijo
