name: Aditya's page
description: Welcome. I am a computer science and mathematics student and this page has a bunch of my projects as well as things that I find interesting.
meta_description: "Computer science, Mathematics."

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Aditya Joshi'
authorTwitter:  '@1adityajoshi'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
